### ISSUE TITLE
Add link

### ISSUE THREAD

**Issue by FabioMike06** [DevSpen/scam-links#113]
### Links To Add

`https://dgiftnow.com/`

### Why Are These Links Bad?
- [X] Phishing
- [ ] Malware
- [X] Scam
- [ ] IP Grabber
- [ ] Other:

**Comment by Juhan280** [comment]
@FabioMike06 Please wrap the links in backticks (`) so others doesn't accidentally click those links

**Comment by FabioMike06** [comment]
My bad, fixed now

**Comment by Qxe5** [comment]
Added the link to https://github.com/DevSpen/scam-links/pull/115 to make it easier for the maintainer.

Note that it has been flagged by Cloudflare but the warning can be dismissed.
