### ISSUE TITLE
Potential "wrong" url? & newe one

### ISSUE THREAD

**Issue by NoobKeksTV** [DevSpen/scam-links#144]
Hi,

The url "discord.net" is in this list. However aftr having some issues with soime bot users, i looked it up and "tested" it a bit.
It currently does not seeme to be active at all. It can not be resolved in the web-browsere and can not be resolved using nmap or ping on linux.
Its whois record says it been registered since 1997 by GoogleDomains sooo idk if its really a Scam url at this point.

Would have made a pr but am on phone, sorry

**Comment by NoobKeksTV** [comment]
Also this site seems pretty Wrong. got it via discord dm today:
"freecash.com"

![image](https://user-images.githubusercontent.com/30929430/175812296-f796297a-8e19-4329-9fb3-4405a115d9c8.png)

**Comment by DevSpen** [comment]
I’ll commit these later today! Thanks.
