### ISSUE TITLE
Scam domain report

### ISSUE THREAD

**Issue by ghost** [DevSpen/scam-links#146]
Hello!

The domain https://dumpishop.ru/ is a fraudulent one and it is designed to swindle payment data.

For example the following link:
https://dumpishop.ru/category/keys

For your convenience I created an account:
Login/password: Scamrrrrrrr/1234567

Sold SCAM keys to pseudo currencies (screenshot 1). After selecting an early "goods" (http://dumpishop.ru/eshop_show/46) offered to top up balance (screenshot 2). After receiving an error, we go to the tab "recharge" (screenshot 3). And choose a random payment system (screenshot 4). After clicking on the top-up button, the fraudulent site asks you to enter the amount in rubles (screenshot 5). Let it be 900. After clicking on the payment button, we get to the fraudulent page with a request to transfer money to a mobile number (screenshot 6) and the text "At the request of our users, we disabled the standard merchant QIWI and set the method of replenishment "Direct transfer".

Screenshots:

https://i.ibb.co/GtGZGsj/67-F3-A3-AB-DDFF-46-B2-82-E9-024-EB68-C9-EE7.jpg
https://i.ibb.co/ssbSPTz/AB0-C12-E7-EB8-D-49-FE-9-B9-D-D856-BACE7-E82.jpg
https://i.ibb.co/5cqQ95s/CF613593-897-E-4-A85-85-AC-CC67-BA0-FC1-C2.jpg
https://i.ibb.co/3rrpzWK/07-EAA358-4-ACA-49-FD-942-A-7-F0-A61129745.jpg
https://i.ibb.co/CnwZrnF/56-BB80-CE-75-D2-4332-A225-10-EFD0-E4-B115.jpg
https://i.ibb.co/QDt06vc/97658-FC9-BB4-C-4-F4-C-9-B72-F2166-A9-B50-F6.jpg

Please take action and block this resource.

**Comment by DevSpen** [comment]
Thanks!
