### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by guyguy303** [DevSpen/scam-links#147]
### Links To Add
Link : https://direct-link.net/468849/charli-damelio-nudepack
When you press enter, it will go to this web page. : https://is.gd/ndmArO

### Why Are These Links Bad?
- [✅] Phishing
- [✅] Malware
- [✅] Scam
- [❓] IP Grabber
- [ ] Other:

**Comment by DevSpen** [comment]
We only block top level URLs not ones with trailing slashes.\
direct-link.net is a real site afaik.
