### ISSUE TITLE
Remove discord.tools

### ISSUE THREAD

**Issue by idkwhyimhereandwhatimdoing** [DevSpen/scam-links#148]
discord.tools is not a scam link, it is used by discord for its internal tools (https://github.com/Delitefully/DiscordLists/blob/master/domains.md)

**Comment by DevSpen** [comment]
> discord.tools is not a scam link, it is used by discord for its internal tools (https://github.com/Delitefully/DiscordLists/blob/master/domains.md)

Thanks
