### ISSUE TITLE
[REQUEST] New link

### ISSUE THREAD

**Issue by PyAres** [DevSpen/scam-links#49]
`discorx.gift`

Full message as reference `@​everyone who will catch this gift?)
https://discorx.gift/TNKLcudUY1zP`

**Comment by Qxe5** [comment]
Yep, this a new one.

**Comment by DevSpen** [comment]
> `discorx.gift`
> 
> Full message as reference `@​everyone who will catch this gift?) https://discorx.gift/TNKLcudUY1zP`

Thank you <3
