### ISSUE TITLE
[REQUEST] Adding New Link

### ISSUE THREAD

**Issue by PyAres** [DevSpen/scam-links#52]
`discordqift.xyz` 

**Full message for context and better avoiding scamming** `Yooooo, Discord is giving away free Nitro!
https://discordqift.xyz/gift/r0mwdFsdjD` 

Also,  `Discord is giving away free Nitro` might be added at malicious terms since i doubt discord will ever giving away free nitro

**Comment by DevSpen** [comment]
I've added the link, the malicious term 'discord is giving' already exists, so that should catch this.
