### ISSUE TITLE
add 

### ISSUE THREAD

**Issue by idkwhyimhereandwhatimdoing** [DevSpen/scam-links#55]

**Comment by Horziox** [comment]
Hello !
You can add this `nice-discord.com` too thanks !

**Comment by PyAres** [comment]
Next time when you add a link remove the http/s because it might be clicked by mistake by someone and would be ridiculous to get scammed like this

**Comment by idkwhyimhereandwhatimdoing** [comment]
> Next time when you add a link remove the http/s because it might be clicked by mistake by someone and would be ridiculous to get scammed like this

oops

**Comment by idkwhyimhereandwhatimdoing** [comment]
add malicous term "specially for you"

**Comment by DPG896** [comment]
Add freedomaini.com. theyre shit scam
