### ISSUE TITLE
Could you add JSON Version ?

### ISSUE THREAD

**Issue by Artlfmj** [DevSpen/scam-links#59]
It can be auto done by a workflow

**Comment by Qxe5** [comment]
I saw an API was in the works. Perhaps it will be included there.

**Comment by nikolaischunk** [comment]
@Artlfmj there is a Repository containing many Scam links as JSON here: [discord-phishing-links](https://github.com/nikolaischunk/discord-phishing-links/blob/main/domain-list.json) :)

**Comment by DevSpen** [comment]
> I saw an API was in the works. Perhaps it will be included there.

Indeed.

**Comment by DevSpen** [comment]
I wouldn’t be oppose to adding a JSON list, but personally I haven’t used GitHub Actions much so I'd need to do some research. If anyone who is more experienced with it wants to make a PR, feel free.

**Comment by Artlfmj** [comment]
I will do so
