### ISSUE TITLE
discordapp.com is an offcial discord site

### ISSUE THREAD

**Issue by Subramanyam-r** [DevSpen/scam-links#81]
![image](https://user-images.githubusercontent.com/80445402/152642049-0199ac26-d2e7-42ad-871e-f7d215ceb449.png)
https://discordapp.com

**Comment by DevSpen** [comment]
Look at the `c` in discord closely.

**Comment by Subramanyam-r** [comment]
Ah Damn, sorry about that, I'm using this with my discord bot and its detecting actual discordapp.com link as a scam link, illl work this out, you may close this

**Comment by DevSpen** [comment]
I made be valid, actually, it could be parsed weirdly by regexes or string methods.
